version: 2
jobs:
  dockerhub-push:
    machine: true
    steps:
      - checkout
      - run: |
          DOCKER_REPOSITORY=appiriodevops/challenges-logstash-conf

          if [ ! -z "$CIRCLE_TAG" ]; then
            UNIQUEID=$CIRCLE_TAG
          fi

          if [ ! -z "$CIRCLE_BRANCH" ]; then
            UNIQUEID=$CIRCLE_BRANCH-$CIRCLE_SHA1
          fi
       - run: | 
          # Build the docker image
          echo Build the docker image $DOCKER_REPOSITORY:$UNIQUEID
          docker build -t $DOCKER_REPOSITORY:$UNIQUEID .
       - run: |
          # Login to docker hub
          docker login -u $DOCKER_USER -p $DOCKER_PASS
       - run: |
          # Deploy image to Docker Hub
          echo Pushing docker image $DOCKER_REPOSITORY:$UNIQUEID
          docker push $DOCKER_REPOSITORY:$UNIQUEID

workflows:
  version: 2
  build-deploy:
    jobs:
      - dockerhub-push:
          filters:
            tags:
              only: /.*/
