version: 2
jobs:
  dockerhub-push:
    machine: true
    environment:
      - DOCKER_REPOSITORY: "appiriodevops/challenges-logstash-conf"
    steps:
      - checkout
      - run: | 
          if [ ! -z "$CIRCLE_TAG" ]; then
            UNIQUEID=$CIRCLE_TAG
          fi

          if [ ! -z "$CIRCLE_BRANCH" ]; then
            UNIQUEID=$CIRCLE_BRANCH-$CIRCLE_SHA1
          fi
          # Build the docker image
          echo Build the docker image $DOCKER_REPOSITORY:$UNIQUEID
          docker build -t $DOCKER_REPOSITORY:$UNIQUEID .

          # Login to docker hub
          docker login -u $DOCKER_USER -p $DOCKER_PASS
          
          # Deploy image to Docker Hub
          echo Pushing docker image $DOCKER_REPOSITORY:$UNIQUEID
          docker push $DOCKER_REPOSITORY:$UNIQUEID

workflows:
  version: 2
  build-deploy:
    jobs:
      - dockerhub-push:
          filters:
            tags:
              only: /.*/
